---

#### Mandatory options ####
# What should be controlling TAEB
ai: 'TAEB::AI::Human'
# How TAEB should communicate with NetHack
interface: Local

#### Interface config #####
# Configure the interface if necessary (telnet and ssh)
#interface_options:
#    Telnet:
#        account: taeb
#        password: pass
#    SSH:
#        account: taeb
#        password: pass

#### Character config #####
# Specify what TAEB should choose when picking a character
#character:
#    role: '*'
#    race: '*'
#    gender: '*'
#    align: '*'

#### Display config #######
# How TAEB should look when you're watching him
# color_method controls how tiles are colored, and glyph_method controls which
# glyphs to display. They can both be changed at runtime as well, see
# doc/debug-commands.txt.
# color_method options: normal, debug, engraving, pathfind, stepped, time, lit
# glyph_method options: normal, floor
#display:
#    color_method: normal
#    glyph_method: normal

#### Debugging config #####
# Configure various debugging plugins for TAEB here
# name for the irc plugin defaults to the bot's name
#debug:
#    console:
#        readline: Gnu
#    irc:
#        server: irc.freenode.net
#        port:   6667
#        channel: "#interhack"
#        name: taeb

#### Logging config #######
#logger:
#    min_level: debug
#    suppress: [moose, undef]
#    log_rotate:
#        dir: logs
#        compress: 1
#    twitter:
#        deaths:
#            username: taeb_deaths
#            password: pass
#        errors:
#            username: taeb_errors
#            password: pass

#### Misc config ##########
# Set this to 1 if you want to run a buggy TAEB overnight; it causes TAEB
# to quit instead of saving on errors; if your TAEB is not particularly
# buggy, you might want to leave this this at 0 so the full state is kept.
#unattended: 0

#### External config ######
# Specify other config files to load here - for example, config files
# containing passwords, or config files specific to a certain ai
#other_config:
#    - etc/site_config.yml
