---

# PUT YOUR CONFIG IN etc/site_config.yml
# This file is versioned, site_config isn't.

interface: Local
personality: ScoreWhore

fight_behavior: Melee

state_file: .TAEB.state

other_config:
    - etc/site_config.yml

