---
interface: Local
brain: RandomWalk

other_config:
    - etc/site_config.yml

interface_options:
    Telnet:
        server: nethack1.devnull.net
        account: Interhack
        password: kool
    Local:
        name: zsh

