---
interface: Local
personality: ScoreWhore

# uncomment this if you want TAEB to remember data between games. experimental!
#state_file: .TAEB.yml

role: Valkyrie
race: Dwarf

fight_behavior: Melee

other_config:
    - etc/site_config.yml

