---

# PUT YOUR CONFIG IN etc/site_config.yml
# This file is versioned, site_config isn't.

interface: Local
personality: ScoreWhore

# uncomment this if you want TAEB to remember data between games. experimental!
#state_file: .TAEB.yml

fight_behavior: Melee

other_config:
    - etc/site_config.yml

