---

# PUT YOUR CONFIG IN etc/site_config.yml
# This file is versioned, site_config isn't.
#other_config:
#    - etc/site_config.yml

ai: 'TAEB::AI::Behavioral::Personality::ScoreWhore'
interface: Local
# Configure the interface if necessary (telnet and ssh)
#interface_options:
#    Telnet:
#        account: taeb
#        password: pass
#    SSH:
#        account: taeb
#        password: pass

# The following give the defaults for options in TAEB

# CRGA
#role: '*'
#race: '*'
#gender: '*'
#align: '*'

# IRC debugging!
# Uncomment the following line to enable.
#IRC:
#    server: irc.freenode.net
#    port:   6667
#    channel: "#interhack"
#    #name: name of bot

# Twitter error reporting!
#twitter:
#    errors:
#        username: user
#        password: pass

# What method to use for coloring of tiles in the display.
# Can change these during runtime as well.
# Current options: normal, debug, engraving, pathfind, stepped, time, lit
#color_method: normal

# How to view the floor glyphs. Changeable during runtime.
# Current options: normal, floor
#glyph_method: normal

# Set this to 1 if you want to run a buggy TAEB overnight; it causes TAEB
# to quit instead of saving on errors; if your TAEB is not particularly
# buggy, you might want to leave this this at 0 so the full state is kept.
# You probably want log_rotation on if you are using this.
#unattended: 0

# Set this to the readline module you'd prefer to use, if the default is broken
#readline: Gnu
